# This is a basic workflow to help you get started with Actions

name: alipan_auto_refresh_token

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    # 每隔1小时刷新一次
    - cron:  '0 */1 * * *'

  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Checkout aliyunpan_config.json
        uses: moonrailgun/branch-filestorage-action@v1.2.0
        with:
          path: aliyunpan_config.json

      - name: Read and show
        run: touch aliyunpan_config.json && cat aliyunpan_config.json          
        
      - name: update aliyunpan_config.json
        run: |
          sudo chmod 777 alipan_refresh_token.sh &&
          sudo ./alipan_refresh_token.sh ${{ secrets.REFRESH_TOKEN }} &&
          sudo cat /etc/aliyunpan/aliyunpan_config.json > aliyunpan_config.json