# This is a basic workflow to help you get started with Actions

name: alipan_auto_sign

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
    - cron:  '5 0 * * *'
    - cron:  '10 0 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: auto_sign_in
        run: |
          sudo apt-get install jq &&
          sudo chmod 777 alipan_auto_check_in.sh &&
          ./alipan_auto_check_in.sh ${{ secrets.REFRESH_TOKEN }} ${{ secrets.PUSHPLUS_TOKEN }}
      - name: Show the timezone
        run: |
          echo "The timezone is $TZ"
          date
